Script started on Sun 01 Mar 2020 10:51:37 PM PST
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ make 
gcc -ansi -std=c99 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o 
gcc -ansi -std=c99 -Wall -c Test_v2.c -o Test.o
gcc -ansi -std=c99 -Wall -c DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -ansi -std=c99 -Wall PhotoLab.o FileIO.o Image.o Test.o  -L. -lFilter -o PhotoLab -lm
gcc -ansi -std=c99 -Wall -c -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall PhotoLab_DEBUG.o FileIO.o Image.o Test.o  -L. -lFilter -o PhotoLabTest -lm
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ ./
PhotoLab*     PhotoLabTest* 
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ ./PhotoLab

-------------------------
1:  Load a PPM image
2:  Save the image in PPM and JPEG format
3:  Change the color image to black and white
4:  Sharpen the image
5:  Change the hue of image
6:  Add Noise to an image
7:  Posterize an image
8:  Add Motion Blur to an image
9:  Enlarge the picture by percentage (COMMING SOON!)
10: Crop a squre portion of the image (COMMING SOON!)
11: Adjust the Brightness and Contrast of an image (COMMING SOON!)
12; Test all functions
13: Exit

-------------------------
Please make your choise: 1
Please input the file name to load: applestore

-------------------------
1:  Load a PPM image
2:  Save the image in PPM and JPEG format
3:  Change the color image to black and white
4:  Sharpen the image
5:  Change the hue of image
6:  Add Noise to an image
7:  Posterize an image
8:  Add Motion Blur to an image
9:  Enlarge the picture by percentage (COMMING SOON!)
10: Crop a squre portion of the image (COMMING SOON!)
11: Adjust the Brightness and Contrast of an image (COMMING SOON!)
12; Test all functions
13: Exit

-------------------------
Please make your choise: 14  2
No image is read.

-------------------------
1:  Load a PPM image
2:  Save the image in PPM and JPEG format
3:  Change the color image to black and white
4:  Sharpen the image
5:  Change the hue of image
6:  Add Noise to an image
7:  Posterize an image
8:  Add Motion Blur to an image
9:  Enlarge the picture by percentage (COMMING SOON!)
10: Crop a squre portion of the image (COMMING SOON!)
11: Adjust the Brightness and Contrast of an image (COMMING SOON!)
12; Test all functions
13: Exit

-------------------------
Please make your choise: 13
You exit the program.
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ ./
PhotoLab*     PhotoLabTest* 
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ ./PhotoLab

-------------------------
1:  Load a PPM image
2:  Save the image in PPM and JPEG format
3:  Change the color image to black and white
4:  Sharpen the image
5:  Change the hue of image
6:  Add Noise to an image
7:  Posterize an image
8:  Add Motion Blur to an image
9:  Enlarge the picture by percentage (COMMING SOON!)
10: Crop a squre portion of the image (COMMING SOON!)
11: Adjust the Brightness and Contrast of an image (COMMING SOON!)
12; Test all functions
13: Exit

-------------------------
Please make your choise: 12
Empty JPEG image (DNL not supported)
*** glibc detected *** ./PhotoLab: free(): invalid pointer: 0x00007f04388e5b10 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3485075e5e]
/lib64/libc.so.6[0x3485078cad]
./PhotoLab[0x401805]
./PhotoLab[0x4018f4]
./PhotoLab[0x400fb1]
./PhotoLab[0x400e98]
/lib64/libc.so.6(__libc_start_main+0x100)[0x348501ed20]
./PhotoLab[0x400ab9]
======= Memory map: ========
00400000-00404000 r-xp 00000000 00:1f 3380293422                         /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLab
00603000-00604000 rw-p 00003000 00:1f 3380293422                         /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLab
017f2000-01813000 rw-p 00000000 00:00 0                                  [heap]
3484c00000-3484c20000 r-xp 00000000 08:01 1966147                        /lib64/ld-2.12.so
3484e20000-3484e21000 r--p 00020000 08:01 1966147                        /lib64/ld-2.12.so
3484e21000-3484e22000 rw-p 00021000 08:01 1966147                        /lib64/ld-2.12.so
3484e22000-3484e23000 rw-p 00000000 00:00 0 
3485000000-348518b000 r-xp 00000000 08:01 1973383                        /lib64/libc-2.12.so
348518b000-348538a000 ---p 0018b000 08:01 1973383                        /lib64/libc-2.12.so
348538a000-348538e000 r--p 0018a000 08:01 1973383                        /lib64/libc-2.12.so
348538e000-3485390000 rw-p 0018e000 08:01 1973383                        /lib64/libc-2.12.so
3485390000-3485394000 rw-p 00000000 00:00 0 
3485800000-3485883000 r-xp 00000000 08:01 1973586                        /lib64/libm-2.12.so
3485883000-3485a82000 ---p 00083000 08:01 1973586                        /lib64/libm-2.12.so
3485a82000-3485a83000 r--p 00082000 08:01 1973586                        /lib64/libm-2.12.so
3485a83000-3485a84000 rw-p 00083000 08:01 1973586                        /lib64/libm-2.12.so
348b800000-348b816000 r-xp 00000000 08:01 1973597                        /lib64/libgcc_s-4.4.7-20120601.so.1
348b816000-348ba15000 ---p 00016000 08:01 1973597                        /lib64/libgcc_s-4.4.7-20120601.so.1
348ba15000-348ba16000 rw-p 00015000 08:01 1973597                        /lib64/libgcc_s-4.4.7-20120601.so.1
7f0434000000-7f0434021000 rw-p 00000000 00:00 0 
7f0434021000-7f0438000000 ---p 00000000 00:00 0 
7f04388e1000-7f0439038000 rw-p 00000000 00:00 0 
7f043905a000-7f043905e000 rw-p 00000000 00:00 0 
7ffd437bf000-7ffd437d4000 rw-p 00000000 00:00 0                          [stack]
7ffd437e9000-7ffd437ea000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Abort (core dumped)
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ valgriun[K[Knd --leak-check=fi;; [K[K[Kull  ./P
PhotoLab*         PhotoLab.c        PhotoLab_DEBUG.o  PhotoLab.o        PhotoLabTest*     
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ valgrind --leak-check=full ./PhotoLabTest 
==6838== Memcheck, a memory error detector
==6838== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==6838== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==6838== Command: ./PhotoLabTest
==6838== 
Empty JPEG image (DNL not supported)
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x40152F: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x5039b40 is 19,200 bytes inside a block of size 7,680,000 alloc'd
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4014FD: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
Empty JPEG image (DNL not supported)
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4015A7: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x578db40 is 19,200 bytes inside a block of size 7,680,000 alloc'd
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401543: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x40291A: Sharpen (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4015DC: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x4c3a7a0 is not stack'd, malloc'd or (recently) free'd
==6838== 
Empty JPEG image (DNL not supported)
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x40161F: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x5ee1b40 is 19,200 bytes inside a block of size 7,680,000 alloc'd
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4015BB: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
Empty JPEG image (DNL not supported)
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x40169C: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x6635b40 is 19,200 bytes inside a block of size 7,680,000 alloc'd
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401633: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
Empty JPEG image (DNL not supported)
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401719: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x6d89b40 is 19,200 bytes inside a block of size 7,680,000 alloc'd
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4016B0: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
Empty JPEG image (DNL not supported)
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4017A0: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x74ddb40 is 19,200 bytes inside a block of size 7,680,000 alloc'd
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x40172D: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401FCC: MotionBlur (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4017D7: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x4c3bbe0 is not stack'd, malloc'd or (recently) free'd
==6838== 
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401FD8: MotionBlur (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4017D7: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x4c3bc20 is not stack'd, malloc'd or (recently) free'd
==6838== 
Empty JPEG image (DNL not supported)
==6838== Invalid free() / delete / delete[] / realloc()
==6838==    at 0x4A06430: free (vg_replace_malloc.c:446)
==6838==    by 0x401440: DeleteImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401814: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==  Address 0x7c31b40 is 19,200 bytes inside a block of size 7,680,000 alloc'd
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4017B4: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 
==6838== HEAP SUMMARY:
==6838==     in use at exit: 53,760,000 bytes in 10 blocks
==6838==   total heap usage: 24 allocs, 24 frees, 53,767,952 bytes allocated
==6838== 
==6838== 0 bytes in 1 blocks are definitely lost in loss record 1 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x402160: Sharpen (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4015DC: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 0 bytes in 1 blocks are definitely lost in loss record 2 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401BCA: MotionBlur (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4017D7: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 0 bytes in 1 blocks are definitely lost in loss record 3 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401CBA: MotionBlur (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4017D7: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 7,680,000 bytes in 1 blocks are possibly lost in loss record 4 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4014FD: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 7,680,000 bytes in 1 blocks are possibly lost in loss record 5 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401633: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 7,680,000 bytes in 1 blocks are possibly lost in loss record 6 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4017B4: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 7,680,000 bytes in 1 blocks are definitely lost in loss record 7 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x401543: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 7,680,000 bytes in 1 blocks are definitely lost in loss record 8 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4015BB: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 7,680,000 bytes in 1 blocks are definitely lost in loss record 9 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x4016B0: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== 7,680,000 bytes in 1 blocks are definitely lost in loss record 10 of 10
==6838==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==6838==    by 0x401393: CreateImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400DD1: LoadImage (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x40172D: AutoTest (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838==    by 0x400B2C: main (in /users/ugrad/2018/fall/osbaldog/sophomore/eecs_22/hw_folder/hw4/PhotoLabTest)
==6838== 
==6838== LEAK SUMMARY:
==6838==    definitely lost: 30,720,000 bytes in 7 blocks
==6838==    indirectly lost: 0 bytes in 0 blocks
==6838==      possibly lost: 23,040,000 bytes in 3 blocks
==6838==    still reachable: 0 bytes in 0 blocks
==6838==         suppressed: 0 bytes in 0 blocks
==6838== 
==6838== For counts of detected and suppressed errors, rerun with: -v
==6838== ERROR SUMMARY: 20 errors from 20 contexts (suppressed: 8 from 6)
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ make clx[Kean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm sharpen.ppm hue.ppm noise.ppm posterize.ppm blur.ppm libFilter.a libFileIO.a
]0;osbaldog@crystalcove:hw4[osbaldog@crystalcove hw4]$ exit
exit

Script done on Sun 01 Mar 2020 10:52:29 PM PST
